from mhs.actions.discovery_pb2 import (
  GenerateDiscoveryScriptRequest,
  GenerateDiscoveryScriptResponse,
)

from mhs.config import ROOT_DIR


def handle(msg: GenerateDiscoveryScriptRequest) -> GenerateDiscoveryScriptResponse:
  template = ROOT_DIR / "templates" / "discovery-script.rsc"
  script = template.read_text()
  script = script.replace("{{hostname}}", msg.hostname)
  script = script.replace("{{primary_mac}}", msg.primary_mac)
  script = script.replace("{{secondary_mac}}", msg.secondary_mac)
  return GenerateDiscoveryScriptResponse(script=f"# Generated by {__file__}\n{script}")

