#!/usr/bin/env python
from mhs.config import ROOT_DIR
from mhs.output import print_info, print_success
from mhs.proto import find_proto_files, generate_proto

print_info("Finding proto files...")
proto_files = find_proto_files()
print_success(f"Found {len(proto_files)} proto files:")
for file in proto_files:
  print(f" - {file.relative_to(ROOT_DIR)}")
print_info("Compiling proto files...")
generate_proto(proto_files)
print_success(f"Compiled {len(proto_files)} proto files.")
