#!/usr/bin/env python

import sys

from mhs.actions.discover import main

if __name__ == "__main__":
  try:
    main.call()
  except Exception as e:
    print(f"Error during discovery: {e}")
    sys.exit(1)
