#!/usr/bin/env python

import sys

from mhs.lan.discover_devices import cli

if __name__ == "__main__":
  try:
    cli.main()
  except Exception as e:
    print(f"Error during discovery: {e}")
    sys.exit(1)
