#!/usr/bin/env python
from mhs.control.mount.cli import main
from mhs.output import print_error

if __name__ == "__main__":
  try:
    main()
  except RuntimeError as e:
    print_error(str(e))
    exit(1)
