#!/usr/bin/env python

import logging
import os
import sys

from mhs.device.ssh.run.handler import main

if __name__ == "__main__":
  logging.basicConfig(
    level=logging.DEBUG if os.getenv("MHS_DEBUG", "0") == "1" else logging.INFO
  )
  main()
else:
  print("This script is intended to be executed directly.")
  sys.exit(1)
