#!/usr/bin/env python

import logging
import os

from mhs.control.execute_service_script.cli import main
from mhs.output import print_error

if __name__ == "__main__":
  logging.basicConfig(
    level=logging.DEBUG if os.getenv("MHS_DEBUG", "0") == "1" else logging.INFO
  )
  try:
    main()
  except RuntimeError as e:
    print_error(str(e))
    exit(1)
