#!/usr/bin/env bash

set -euo pipefail

# Set up Immich. Safe to run multiple times.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SERVICE_DIR="$( cd "$SCRIPT_DIR/" && pwd )"
ROOT_DIR="$( cd "$SERVICE_DIR/../../" && pwd )"
LIB_DIR="$ROOT_DIR/lib"
source "$LIB_DIR/common.sh"
source "$LIB_DIR/services.sh"
source "$LIB_DIR/ensure_sbin_path.sh"
source "$LIB_DIR/env.sh"
load_env "$ROOT_DIR"
load_env "$SERVICE_DIR"

if [[ -z "$MHS_FLEET_FILEPATH" ]]; then
  print_error "MHS_FLEET_FILEPATH not set"
  exit 1
else
  echo "Using fleet file path: $MHS_FLEET_FILEPATH"
fi

if [[ -z "$MHS_CNAME_TARGET" ]]; then
  print_error "MHS_CNAME_TARGET not set"
  exit 1
else
  echo "Using CNAME target: $MHS_CNAME_TARGET"
fi

SKIP_STEPS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-steps)
      # split comma-separated list into array
      IFS=',' read -r -a parts <<< "$2"
      SKIP_STEPS+=("${parts[@]}")
      shift 2
      ;;
    *)
			# drop unrecognized args
      shift
      ;;
  esac
done

# Iterate over step files, skipping any in SKIP_STEPS
STEP_FILES=("$SCRIPT_DIR"/init-steps/*.sh)
IFS=$'\n' STEP_FILES=($(sort <<<"${STEP_FILES[*]}"))
unset IFS

for file in "${STEP_FILES[@]}"; do
  filename="$(basename "$file" .sh)"
  step_num="${filename%%-*}" # extract numeric prefix

  if skip_step "$step_num"; then
    echo "🦘 $filename"
    continue
  fi

  echo "🪜  $filename"
  source "$file"
done

print_success "Ingress setup complete!"