#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$SCRIPT_DIR/../../" && pwd )"
source "$ROOT_DIR/.env"
source "$ROOT_DIR/lib/common.sh"
source "$ROOT_DIR/lib/services.sh"
echo "Running health checks..."
systemctl status nginx
