from mhs.device.discover import TEMPLATES_DIR


def generate_device_discovery_script(hostname: str, primary_mac: str, secondary_mac: str) -> str:
  template = TEMPLATES_DIR / "discovery-script.rsc"
  script = template.read_text()
  script = script.replace("{{hostname}}", hostname)
  script = script.replace("{{primary_mac}}", primary_mac)
  script = script.replace("{{secondary_mac}}", secondary_mac)
  return f"# Generated by {__file__}\n{script}"
