#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_DIR="$(cd "$SCRIPT_DIR/../" && pwd)"
ROOT_DIR="$(cd "$SERVICE_DIR/../../" && pwd)"
LIB_DIR="$ROOT_DIR/lib"
source "$LIB_DIR/common.sh"

cd "$SERVICE_DIR"
docker compose down 