# Creates individual site config files for each service

# Check if nginx is installed
if ! command -v nginx &> /dev/null; then
	print_error "nginx not installed, are you running on the correct machine?"
	exit 1
fi

NGINX_SITES_AVAILABLE="/etc/nginx/sites-available"
if [[ ! -d "$NGINX_SITES_AVAILABLE" ]]; then
	print_error "nginx sites-available directory not found: $NGINX_SITES_AVAILABLE"
	exit 1
fi

NGINX_SITES_ENABLED="/etc/nginx/sites-enabled"
if [[ ! -d "$NGINX_SITES_ENABLED" ]]; then
	print_error "nginx sites-enabled directory not found: $NGINX_SITES_ENABLED"
	exit 1
fi

if ! sudo test -w "$NGINX_SITES_AVAILABLE" || ! sudo test -w "$NGINX_SITES_ENABLED"; then
	print_error "Insufficient permissions to write to nginx configuration directories. Please run as a user with sudo privileges."
	exit 1
fi

if [[ -f "$NGINX_SITES_ENABLED/default" ]]; then
	print_status "Removing default nginx site configuration..."
	sudo rm -f "$NGINX_SITES_ENABLED/default"
fi

# Set up resolver and http-level directives at /etc/nginx/conf.d/
# This avoids duplicate resolver errors across multiple server blocks
# and keeps ingress-specific settings separate and idempotent
if [[ ! -f "$NGINX_CONF" ]] || env_bool MHS_INGRESS_NUKE_NGINX_CONF; then
	print_status "Creating nginx ingress global configuration..."
	sudo tee "$NGINX_CONF" >/dev/null << 'EOF'
# Ingress DNS resolver for static hostnames
resolver 192.168.1.1 valid=10s;
resolver_timeout 5s;

# Allow long domain names
server_names_hash_bucket_size 64;
EOF
	cat $NGINX_CONF
fi

if [[ ${#SERVICES[@]} -eq 0 ]]; then
	print_warning "No services to configure in nginx"
	return 0
fi

# Process each service
config_count=${config_count:-0}
for service in "${SERVICES[@]}"; do
	print_status "Processing service: $service"
	IFS='|' read -r DOMAIN HOSTNAME PORT <<< "$service"
	
	# Sanitize domain for filename
	CONFIG_NAME="${DOMAIN//./}"
	CONFIG_FILE="$NGINX_SITES_AVAILABLE/ingress-$CONFIG_NAME"
	ENABLED_LINK="$NGINX_SITES_ENABLED/ingress-$CONFIG_NAME"

	print_status "Creating nginx config: $DOMAIN -> $HOSTNAME:$PORT"
	
	# Create individual service config (resolver at http level, not here)
	sudo tee "$CONFIG_FILE" >/dev/null << EOF
# Generated by ingress/init for $DOMAIN
server {
	listen 80;
	server_name $DOMAIN;
	client_max_body_size 4G;

	location / {
		set \$backend "http://$HOSTNAME:$PORT";
		proxy_pass \$backend;
		proxy_http_version 1.1;
		proxy_set_header Host \$host;
		proxy_set_header X-Real-IP \$remote_addr;
		proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto \$scheme;
		proxy_set_header Upgrade \$http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_read_timeout 86400;
	}
}
EOF
	
	# Create symlink if it doesn't exist
	if [[ ! -L "$ENABLED_LINK" ]]; then
		sudo ln -sf "$CONFIG_FILE" "$ENABLED_LINK"
	fi
	
	print_success "nginx config created: $DOMAIN"
	((config_count += 1))
done

print_status "Testing nginx configuration..."
if ! sudo nginx -t 2>&1 | grep -q "successful"; then
	print_error "nginx configuration test failed"
	sudo nginx -t
	return 1
fi
print_success "nginx configuration is valid"

print_status "Reloading nginx..."
sudo systemctl reload nginx
print_success "nginx reloaded"

print_success "Configured $config_count nginx sites"
