#!/usr/bin/env bash
# https://docs.immich.app/administration/backup-and-restore/

set -euo pipefail
SERVICE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$SERVICE_DIR/../../" && pwd )"
source "$ROOT_DIR/lib/common.sh"
source "$ROOT_DIR/lib/services.sh"
install_docker
source "$ROOT_DIR/lib/env.sh"
load_env "$ROOT_DIR"
load_env "$SERVICE_DIR"
if env_bool MHS_DEBUG; then
  set -x
fi

# Relative to ROOT_DIR
[[ $# -ge 1 ]] || { print_error "Usage: $0 <path-to-backup-archive>"; exit 1; }
backup_path="$(realpath "$1")"

if [[ ! -f "$backup_path" ]]; then
  print_error "Backup file not found: $backup_path"
  exit 1
fi

print_status "Restoring Immich DB from: $backup_path"

cd "$SERVICE_DIR"
docker compose down -v  # CAUTION! Deletes all Immich data to start from scratch
## Uncomment the next line and replace DB_DATA_LOCATION with your Postgres path to permanently reset the Postgres database
# rm -rf DB_DATA_LOCATION # CAUTION! Deletes all Immich data to start from scratch
docker compose pull             # Update to latest version of Immich (if desired)
docker compose create           # Create Docker containers for Immich apps without running them
docker start immich_postgres    # Start Postgres server
sleep 10                        # Wait for Postgres server to start up
# Check the database user if you deviated from the default
gunzip --stdout $backup_path \
| sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" \
| docker exec -i immich_postgres psql --dbname=postgres --username="$DB_USERNAME"  # Restore Backup
docker compose up -d            # Start remainder of Immich apps

print_success "Immich DB restoration complete!"
print_status "You need to manually move your files into the UPLOAD_LOCATION: $UPLOAD_LOCATION"
