#!/usr/bin/env python
"""
Ensure __init__.py files exist in subdirs.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from mhs.output import print_error, print_info

if __name__ != "__main__":
  print_error("This script is intended to be executed directly.")
  sys.exit(1)

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument(
  "root_dir",
  type=Path,
  help="Path to start from (__init__.py must exist in the root directory already).",
)

args = parser.parse_args()

for subdir in args.root_dir.rglob("*"):
  if subdir.is_dir():
    init_file = subdir / "__init__.py"
    if not init_file.exists():
      print_info(f"Creating {init_file}")
      init_file.touch()
