from mhs.config import ROOT_DIR
from mhs.discovery.generate_device_discovery_script.messages_pb2 import (
  GenerateDiscoveryScriptRequest,
  GenerateDiscoveryScriptResponse,
)


def handle(msg: GenerateDiscoveryScriptRequest) -> GenerateDiscoveryScriptResponse:
  template = ROOT_DIR / "templates" / "discovery-script.rsc"
  script = template.read_text()
  script = script.replace("{{hostname}}", msg.hostname)
  script = script.replace("{{primary_mac}}", msg.primary_mac)
  script = script.replace("{{secondary_mac}}", msg.secondary_mac)
  script_content = f"# Generated by {__file__}\n{script}"
  return GenerateDiscoveryScriptResponse(script_content=script_content)
