from jinja2 import Template

from mhs.discovery.generate_device_discovery_script import TEMPLATE_DIR
from mhs.discovery.generate_device_discovery_script.messages_pb2 import (
  GenerateDiscoveryScriptRequest,
  GenerateDiscoveryScriptResponse,
)


def handle(msg: GenerateDiscoveryScriptRequest) -> GenerateDiscoveryScriptResponse:
  template_file = TEMPLATE_DIR / "discovery-script.rsc.jinja2"
  template_content = template_file.read_text()
  template = Template(template_content)

  script = template.render(
    hostname=msg.hostname,
    primary_mac=msg.primary_mac,
    secondary_mac=msg.secondary_mac,
  )

  script_content = f"# Generated by {__file__}\n{script}"
  return GenerateDiscoveryScriptResponse(script_content=script_content)
