#!/usr/bin/env bash
set -euo pipefail
source ".env"

backup_path="$(realpath "$1")"
if [[ -f "$backup_path" ]]; then
  echo "Restoring Immich DB from: $backup_path"
else
  echo "Backup file not found: $1"
  exit 1
fi

echo "Stopping Immich apps and removing volumes..."
docker compose down -v

echo "Deleting existing Immich database data from $DB_DATA_LOCATION..."
rm -rf $DB_DATA_LOCATION

echo "Update to latest version of Immich"
docker compose pull

echo "Creating Docker containers for Immich apps without running them"
docker compose create

echo "Starting ing Postgres container..."
docker start immich_postgres

echo "Waiting for Postgres to start..."
sleep 10

# Check the database user if you deviated from the default
echo "Restoring database from backup..."
gunzip --stdout $backup_path \
| sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" \
| docker exec -i immich_postgres psql --dbname=postgres --username="$DB_USERNAME"  # Restore Backup

echo "Restarting containers..."
docker compose up -d

echo "Immich DB restoration complete!"
echo "You need to manually move your files into the UPLOAD_LOCATION: $UPLOAD_LOCATION"